app:
  id: sso # 应用全局唯一的身份标识
apollo:
  meta: http://192.168.62.132:8080 # Apollo Meta Server 地址
  cacheDir: ./config # 自定义本地配置文件缓存路径
  bootstrap:
    enabled: true # 设置在应用启动阶段就加载 Apollo 配置
    eagerLoad:
      enabled: true

spring:
  jasypt:
    encryptor:
      password: koushenhai5201314wumeihua
  boot:
    admin:
      client:
        url: http://192.168.62.1:5000/monitor
        username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
        password: ENC(nj35dMcOWEmR5EASEZR3yfaT4IdT9TPm)
        instance:
          service-base-url: http://192.168.62.1:${server.port}
          prefer-ip: true
  redis:
    database: 0
    host: 192.168.62.128
    port: 6379
    timeout: 6000ms #连接超时时长（毫秒）
    jedis:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示无极限）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池最大空闲连接
        min-idle: 5 #连接池最小空间连接
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.62.128:3306/kcloud?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
      password: ENC(SX9kPzLDaZb9kGOl2QBziw==)
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      web-stat-filter:
        enabled: true
        url-pattern: /**
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ENC(7j+MYBNM2fhq8WST3DE3WA==)
        login-password: ENC(nj35dMcOWEmR5EASEZR3yfaT4IdT9TPm)
        allow:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

oauth:
  zfb:
    app_id: 2019121269782969
    merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDLd4jlNtQJzsa317eLP/Gr5HL+qg7rYEMfJJjfO3POm2qLLl+0r5E2HFT+vuyYRX36Qlq3q8l+eUk+9DsgT0x5Mb3nI+2lAQ6eDcq0c8Sa08omvrvzq9ckQnORXjPu4tvWk1vyNAezfJtAMJfrMNPmRJtdDjPwIHoyXA5o+HOW5x5KObLWA+WMAgofrC0I5XkFCU3nAZ9KsssNJvrcw9tDm2G3WG+QfHvr8hjdIw/Sax1+iDZ7AIkY9ccDWf32LPAvcph8rj9r74W+/nsuk5VQKCsy99sK0lDKbRDhLHNprmuqQgWZDMWc+sA50LWBoA6Zj26diyC+Mq/NHXyGFrhNAgMBAAECggEACOkFL7SE+KD7htWFji2QscxhVNGxsZEXn2eE4lHCMowP0GSJgGon28zF1BocVlbEu47oVh7JxiYdlQoxBKs0WCJbhKHIKG+xai6Eb/6Z34Xi1muH45Xk6AuY8AbGE3IP2oe9gQ/SPoP4cIkwPfZ3cSAUBbE3iQ6DC22InAQ1W6hTVW5WY02ttMpKxJ4P8mKywvR4mbVVvzRcv197ARL+bG9AhjY6yVaOlyFt+54/BEDBtj8BlIf8gJp09l5NcSNjs9Nu4iVRuMtfHKHQjP/b5BSI0gLRU26eabQjDZGly80yht38wQect7CtMkssSS7lD3Haf7NTXAUojQ9WkVm2QQKBgQD4gKNnU2eg7c/xvavzkRsYU7eFtZ7jDRhC/k+IptWwOmExgSuC7BUCqykcys7Xtykr5fiUjbastNVvEcHUiNnS6T9dCvFoOMCq01DcmCWMKxSi4rE5NVM+yl8fOv51t4EtNOa9jZPejdbZJTxNsu4nO25JtkHG3/1gMpK+MlZNOQKBgQDRmw4EAUQ6aFHjrKzc1v9CZWQEp0/fsY1VmF2RM8otOlDCXeQMnSYCHJGVCv6IKYyx/0D5j6sscFml1GcemD6GEDkOWOwgsH+tbdNVjPAvrx4n7jCR7zDEjAwXrIoZwOUkaBv79PYo8y+ZCMXFE87IS9n3/LW41Wur0Mjb4TIXtQKBgQCouxe4ac5cW/0sxD/EEwvVucpL1KU8v8BwhKLWQ4mmrg0egvlbXRdrB3LT5PULTYd8Eht2Kr8Vh3fAgcsdl4pnhg6LC4oc3SQdGXy3O+uKwBmz+76f/JA4e0qZNwJeRapFWr0tibsUizSNnpXSoCLKqrTZAhKpiZ9OOSigUid9KQKBgAoF/i+W1+prHq9ijImrBl3od1X5okoyNW4IcUEGVv6+sSn6T3OC+FRVhWi5M97TDdVdPYAxrJ/dZ4wUkjHWWfcTQ4c6HWCa0CA9BkQrDzlYiHqkW1I/O/fKMrHXIGuG2+5XxC7SUgs3Reltj/eSsOrHJc9EGHSUUCfRPim1pS2ZAoGBAIsvs2hQAEpRFKObyaoMvGi4V8jZ8dM2HwaPsnC2Poph9TxA7woruqXzBxLdRB/pjBq5fUZHLwGVq1MuSYwduX3HA5HvaNvzh5qQKOa5/OSPnqr58RWu7y4vj2WY5j9bGBtwMCsVu4igPYDYWlYylXqKUS20kGP1QQBcpsXKhfKn
    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxFEea4LPRXaqPPRZc0UgIDajZEfHGFxJG8nmktcbbJu0J7HDUjdO0OkQvEuyBxClZqixaCpGLnmzVA/up/wdZpnJPLBEwL/+Umx4E99AUsU6WKXnFkIwZY8BAaXYQUhZnQw4sr95flHnmoKNC46k9GXeWts5XLMXG8fGzSzgeTYk0DJrpHHOPELk8R1lQHLwNpeCLb+8h7guhm8BhRiTsdLNfZ/2fEe6LVIUYUKue+kPOIhih9YurC3bf/zxWJzd/ujnNhfXccJ5/vxOtm2helpLo58bKbmiquwcjq+v1wS+dsrrWg5Nbt6SCc4IAx7JtygEXoouTiz0bhBG53cSJwIDAQAB
    encrypt_type: RSA2
    charset: utf-8
    sign_type: json
    gateway_url: https://openapi.alipay.com/gateway.do
    login_url: http://localhost:9999