#/*
# * Copyright (c) 2022 KCloud-Platform-Alibaba Authors. All Rights Reserved.
# * <p>
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# * <p>
# * http://www.apache.org/licenses/LICENSE-2.0
# * <p>
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# */
# server
server:
  port: 10000
  ssl:
    # 开启证书
    enabled: @SSL-ENABLED@
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: true
  forward-headers-strategy: framework
#spring
spring:
  application:
    name: @pom.parent.artifactId@
  profiles:
    # 环境 dev|test|prod
    active: @PROFILE-ACTIVE@
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*

flowable:
  # 只保存审批记录
  history-level: audit
  # 开启异步作业执行程序激活
  async-history-executor-activate: true
  # 关闭idm
  idm:
    enabled: false
  # 开启历史记录清除
  enable-history-cleaning: true
  # 一周后清理历史记录
  history-cleaning-after: 7

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml