jasypt:
  encryptor:
    password: koushenhai5201314wumeihua
server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: laokou-oauth2
  messages:
    encoding: UTF-8
    basename: i18n/messages
  profiles:
    # 环境 dev|test|prod
    active: @profile.active@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体类扫描，多个package用头号或分号分隔
  type-aliases-package: org.laokou.oauth2.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID",ASSIGN_ID:"分布式ID"
      id-type: ASSIGN_ID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #db-type:mysql
      logic-delete-value: 1 #逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为 0）
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
